import 'package:flutter/material.dart';
import '../../widgets/premium_ui_components.dart';
import 'package:share_plus/share_plus.dart';
import 'package:provider/provider.dart';
import '../../services/baby_data_repository.dart';

class BabyBookGeneratorScreen extends StatefulWidget {
  const BabyBookGeneratorScreen({super.key});

  @override
  State<BabyBookGeneratorScreen> createState() => _BabyBookGeneratorScreenState();
}

class _BabyBookGeneratorScreenState extends State<BabyBookGeneratorScreen> {
  bool _isGenerating = false;
  bool _isFinished = false;
  
  String _babyName = "Baby";
  final int _ageMonths = 3;
  double _weightKg = 6.5;

  @override
  void initState() {
    super.initState();
    _loadProfile();
  }

  Future<void> _loadProfile() async {
    final repo = context.read<BabyDataRepository>();
    try {
      final p = await repo.getProfile();
      if (p != null) {
        if (p['baby_name'] != null) _babyName = p['baby_name'];
        if (p['birth_weight'] != null) _weightKg = (p['birth_weight'] as num).toDouble() + 3.0; // Assume growth
      }
    } catch (_) {}
    if (mounted) setState(() {});
  }

  void _generatePoster() async {
    setState(() {
      _isGenerating = true;
      _isFinished = false;
    });
    
    // Simulate AI generation process
    await Future.delayed(const Duration(seconds: 3));
    
    if (mounted) {
      setState(() {
        _isGenerating = false;
        _isFinished = true;
      });
    }
  }

  void _sharePoster() {
    Share.share('Check out $_babyName\'s $_ageMonths-month milestone! Generated by the Neo App.');
  }

  @override
  Widget build(BuildContext context) {
    final colors = PremiumColors(context);
    final typo = PremiumTypography(context);

    return PremiumScaffold(
      appBar: AppBar(
        title: Text('Baby Book Generator', style: typo.h2),
        backgroundColor: Colors.transparent,
        elevation: 0,
        centerTitle: true,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Create Milestone Posters', style: typo.h1.copyWith(fontSize: 32)),
              const SizedBox(height: 8),
              Text('Our AI takes your baby\'s latest stats and generates beautiful, perfectly sized typography posters ready for Instagram or your digital baby book.', style: typo.body.copyWith(color: colors.textSecondary)),
              
              const SizedBox(height: 32),

              if (!_isFinished && !_isGenerating) ...[
                Text('Poster Details', style: typo.h2),
                const SizedBox(height: 16),
                _buildInputTile('Milestone Age', '$_ageMonths Months', Icons.cake_rounded, colors, typo),
                const SizedBox(height: 12),
                _buildInputTile('Current Weight', '${_weightKg.toStringAsFixed(1)} kg', Icons.scale_rounded, colors, typo),
                const SizedBox(height: 12),
                _buildInputTile('Favorite Activity', 'Smiling at Mom', Icons.favorite_rounded, colors, typo),
                const SizedBox(height: 32),
                SizedBox(
                  width: double.infinity,
                  child: PremiumActionButton(
                    label: 'Generate Poster',
                    icon: Icons.auto_awesome_rounded,
                    color: colors.gentlePurple,
                    onTap: _generatePoster,
                  ),
                ),
              ],

              if (_isGenerating)
                Center(
                  child: Padding(
                    padding: const EdgeInsets.symmetric(vertical: 48),
                    child: Column(
                      children: [
                        const CircularProgressIndicator(),
                        const SizedBox(height: 24),
                        Text('Designing typography...', style: typo.bodyBold.copyWith(color: colors.gentlePurple)),
                      ],
                    ),
                  ),
                ),

              if (_isFinished) ...[
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text('Your Poster', style: typo.h2),
                    TextButton.icon(
                      onPressed: () => setState(() => _isFinished = false),
                      icon: Icon(Icons.refresh_rounded, color: colors.sereneBlue, size: 18),
                      label: Text('Remake', style: typo.bodyBold.copyWith(color: colors.sereneBlue)),
                    ),
                  ],
                ),
                const SizedBox(height: 16),
                
                // Generated Poster Preview
                AspectRatio(
                  aspectRatio: 4/5, // Instagram Portrait
                  child: Container(
                    width: double.infinity,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(24),
                      gradient: LinearGradient(
                        begin: Alignment.topLeft,
                        end: Alignment.bottomRight,
                        colors: [colors.gentlePurple, colors.sereneBlue], // Assuming primary is gentlePurple/sereneBlue
                      ),
                      boxShadow: [
                        BoxShadow(color: colors.gentlePurple.withValues(alpha: 0.3), blurRadius: 20, offset: const Offset(0, 10)),
                      ],
                    ),
                  child: Stack(
                    children: [
                      // Decorative elements
                      Positioned(
                        top: -50, right: -50,
                        child: Container(
                          width: 200, height: 200,
                          decoration: BoxDecoration(
                            shape: BoxShape.circle,
                            color: Colors.white.withValues(alpha: 0.1),
                          ),
                        ),
                      ),
                      Positioned(
                        bottom: -30, left: -30,
                        child: Container(
                          width: 150, height: 150,
                          decoration: BoxDecoration(
                            shape: BoxShape.circle,
                            color: Colors.white.withValues(alpha: 0.1),
                          ),
                        ),
                      ),
                      
                      // Text Content
                      Padding(
                        padding: const EdgeInsets.all(32),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Text('HI I AM', style: typo.caption.copyWith(color: Colors.white70, letterSpacing: 3)),
                            const SizedBox(height: 8),
                            Text(_babyName.toUpperCase(), style: typo.h1.copyWith(color: Colors.white, fontSize: 48, height: 1.0)),
                            const SizedBox(height: 24),
                            
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                              decoration: BoxDecoration(
                                color: Colors.white.withValues(alpha: 0.2),
                                borderRadius: BorderRadius.circular(100),
                              ),
                              child: Text('I am $_ageMonths Months Old Today! 🎉', style: typo.bodyBold.copyWith(color: Colors.white)),
                            ),
                            
                            const SizedBox(height: 32),
                            Text('I WEIGH', style: typo.caption.copyWith(color: Colors.white70, letterSpacing: 2)),
                            Text('${_weightKg.toStringAsFixed(1)} kg', style: typo.h2.copyWith(color: Colors.white, fontSize: 32)),
                            
                            const SizedBox(height: 24),
                            Text('I LOVE', style: typo.caption.copyWith(color: Colors.white70, letterSpacing: 2)),
                            Text('Smiling at Mom! 🥺', style: typo.h2.copyWith(color: Colors.white, fontSize: 32)),
                          ],
                        ),
                      ),
                    ],
                  ), // Closes Stack
                ), // Closes Container
              ), // Closes AspectRatio
              
              const SizedBox(height: 32),
                
                Row(
                  children: [
                    Expanded(
                      child: PremiumActionButton(
                        label: 'Save Profile',
                        icon: Icons.download_rounded,
                        color: colors.sereneBlue,
                        onTap: () {
                          ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Saved to camera roll!')));
                        },
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: PremiumActionButton(
                        label: 'Share',
                        icon: Icons.ios_share_rounded,
                        color: colors.warmPeach,
                        onTap: _sharePoster,
                      ),
                    ),
                  ],
                ),
              ],
              
              const SizedBox(height: 80),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildInputTile(String label, String value, IconData icon, PremiumColors colors, PremiumTypography typo) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: colors.surfaceMuted,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.transparent),
      ),
      child: Row(
        children: [
          Icon(icon, color: colors.gentlePurple),
          const SizedBox(width: 16),
          Expanded(child: Text(label, style: typo.body.copyWith(color: colors.textSecondary))),
          Text(value, style: typo.bodyBold),
          const SizedBox(width: 8),
          Icon(Icons.edit_rounded, size: 16, color: colors.textMuted),
        ],
      ),
    );
  }
}
